"""All sensor entities."""

from homeassistant.components.sensor import SensorDeviceClass, SensorEntityDescription
from homeassistant.const import (
    PERCENTAGE,
    UnitOfElectricPotential,
    UnitOfEnergy,
    UnitOfLength,
    UnitOfSpeed,
    UnitOfTemperature,
)

from . import OceanPulseSensorEntityDescription as SensorEntityDesc

SENSORS_DIGITAL_TWIN: tuple[SensorEntityDescription, ...] = (
    # Battery / Range
    SensorEntityDesc(
        key="SOC",
        name="Battery",
        icon="mdi:battery-70",
        device_class=SensorDeviceClass.BATTERY,
        native_unit_of_measurement=PERCENTAGE,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="SOH",
        name="Battery health",
        icon="mdi:battery-heart",
        device_class=SensorDeviceClass.BATTERY,
        native_unit_of_measurement=PERCENTAGE,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="HV_CAP",
        name="HV battery capacity",
        icon="mdi:car-electric",
        device_class=SensorDeviceClass.ENERGY_STORAGE,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="BATTERY_12V",
        name="12V battery",
        icon="mdi:car-battery",
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="RANGE",
        name="Range",
        icon="mdi:map-marker-distance",
        device_class=SensorDeviceClass.DISTANCE,
        native_unit_of_measurement=UnitOfLength.KILOMETERS,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="MILEAGE",
        name="Odometer",
        icon="mdi:counter",
        device_class=SensorDeviceClass.DISTANCE,
        native_unit_of_measurement=UnitOfLength.KILOMETERS,
        value=lambda data, key: data[key],
    ),
    # Temperature
    SensorEntityDesc(
        key="AMBIENT_TEMP",
        name="Ambient temperature",
        icon="mdi:thermometer",
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="OUTDOOR_TEMP",
        name="Outdoor temperature",
        icon="mdi:thermometer",
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="DRIVER_TEMP",
        name="Driver temp setpoint",
        icon="mdi:thermometer",
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="PASS_TEMP",
        name="Passenger temp setpoint",
        icon="mdi:thermometer",
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        value=lambda data, key: data[key],
    ),
    # Seat heat (int 0-4: 0=Unknown, 1=High, 2=Medium, 3=Low, 4=Off)
    SensorEntityDesc(
        key="SEAT_HEAT_DRIVER",
        name="Driver seat heat",
        icon="mdi:car-seat-heater",
        device_class=None,
        native_unit_of_measurement=None,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="SEAT_HEAT_PASSENGER",
        name="Passenger seat heat",
        icon="mdi:car-seat-heater",
        device_class=None,
        native_unit_of_measurement=None,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="SEAT_HEAT_REAR_LEFT",
        name="Rear left seat heat",
        icon="mdi:car-seat-heater",
        device_class=None,
        native_unit_of_measurement=None,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="SEAT_HEAT_REAR_RIGHT",
        name="Rear right seat heat",
        icon="mdi:car-seat-heater",
        device_class=None,
        native_unit_of_measurement=None,
        value=lambda data, key: data[key],
    ),
    # Climate
    SensorEntityDesc(
        key="CLIMATE_ON",
        name="Climate",
        icon="mdi:fan",
        device_class=None,
        native_unit_of_measurement=None,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="CLIMATE_STATE",
        name="Climate state",
        icon="mdi:fan",
        device_class=None,
        native_unit_of_measurement=None,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="AC_STATE",
        name="AC state",
        icon="mdi:air-conditioner",
        device_class=None,
        native_unit_of_measurement=None,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="AC_AUTO",
        name="AC auto",
        icon="mdi:air-conditioner",
        device_class=None,
        native_unit_of_measurement=None,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="FAN_SPEED",
        name="Fan speed",
        icon="mdi:fan",
        device_class=None,
        native_unit_of_measurement=None,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="RECIRCULATION",
        name="Recirculation",
        icon="mdi:air-filter",
        device_class=None,
        native_unit_of_measurement=None,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="FRONT_DEFROST",
        name="Front defrost",
        icon="mdi:car-defrost-front",
        device_class=None,
        native_unit_of_measurement=None,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="REAR_DEFROST",
        name="Rear defrost",
        icon="mdi:car-defrost-rear",
        device_class=None,
        native_unit_of_measurement=None,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="STEERING_WHEEL_HEAT",
        name="Steering wheel heat",
        icon="mdi:steering",
        device_class=None,
        native_unit_of_measurement=None,
        value=lambda data, key: data[key],
    ),
    # Charging
    SensorEntityDesc(
        key="CHARGING",
        name="Charging",
        icon="mdi:ev-plug-type2",
        device_class=None,
        native_unit_of_measurement=None,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="AC_CHARGE_LAMP",
        name="AC charge lamp",
        icon="mdi:ev-plug-type2",
        device_class=None,
        native_unit_of_measurement=None,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="AC_CHARGE_LAMP_COLOR",
        name="AC charge lamp color",
        icon="mdi:ev-plug-type2",
        device_class=None,
        native_unit_of_measurement=None,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="DC_CHARGE_LAMP",
        name="DC charge lamp",
        icon="mdi:ev-plug-ccs2",
        device_class=None,
        native_unit_of_measurement=None,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="DC_CHARGE_LAMP_COLOR",
        name="DC charge lamp color",
        icon="mdi:ev-plug-ccs2",
        device_class=None,
        native_unit_of_measurement=None,
        value=lambda data, key: data[key],
    ),
    # Doors / Locks
    SensorEntityDesc(
        key="LOCK_STATUS",
        name="Lock status",
        icon="mdi:car-door-lock",
        device_class=None,
        native_unit_of_measurement=None,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="DOOR_FL_OPEN",
        name="Door front left",
        icon="mdi:car-door",
        device_class=None,
        native_unit_of_measurement=None,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="DOOR_FR_OPEN",
        name="Door front right",
        icon="mdi:car-door",
        device_class=None,
        native_unit_of_measurement=None,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="DOOR_RL_OPEN",
        name="Door rear left",
        icon="mdi:car-door",
        device_class=None,
        native_unit_of_measurement=None,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="DOOR_RR_OPEN",
        name="Door rear right",
        icon="mdi:car-door",
        device_class=None,
        native_unit_of_measurement=None,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="TRUNK_OPEN",
        name="Trunk",
        icon="mdi:car-back",
        device_class=None,
        native_unit_of_measurement=None,
        value=lambda data, key: data[key],
    ),
    # Location
    SensorEntityDesc(
        key="lat",
        name="Location latitude",
        icon="mdi:map-marker-radius",
        device_class=None,
        native_unit_of_measurement="°",
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="lon",
        name="Location longitude",
        icon="mdi:map-marker-radius",
        device_class=None,
        native_unit_of_measurement="°",
        value=lambda data, key: data[key],
    ),
    # General / System
    SensorEntityDesc(
        key="POWER_MODE",
        name="Power mode",
        icon="mdi:power",
        device_class=None,
        native_unit_of_measurement=None,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="SCU_CONNECTED",
        name="SCU connected",
        icon="mdi:car-connected",
        device_class=None,
        native_unit_of_measurement=None,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="SYNC_ON",
        name="Sync",
        icon="mdi:sync",
        device_class=None,
        native_unit_of_measurement=None,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="installed_version",
        name="Firmware version",
        icon="mdi:car-info",
        device_class=None,
        native_unit_of_measurement=None,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="installed_build",
        name="Firmware build",
        icon="mdi:car-info",
        device_class=None,
        native_unit_of_measurement=None,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="last_update",
        name="Last updated",
        icon="mdi:clock-outline",
        device_class=None,
        native_unit_of_measurement=None,
        value=lambda data, key: data[key],
        format="%Y-%m-%d %H:%M:%S",
    ),
)

# No separate car-settings endpoint in the OceanPulse API.
SENSORS_CAR_SETTINGS: tuple[SensorEntityDescription, ...] = ()

SENSORS_tripSTAT: tuple[SensorEntityDescription, ...] = (
    SensorEntityDesc(
        key="tripstat_distance",
        name="Trip distance",
        icon="mdi:map-marker-distance",
        device_class=SensorDeviceClass.DISTANCE,
        native_unit_of_measurement=UnitOfLength.KILOMETERS,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="tripstat_duration",
        name="Trip duration",
        icon="mdi:car-clock",
        device_class=SensorDeviceClass.DURATION,
        native_unit_of_measurement=None,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="tripstat_battery",
        name="Trip energy",
        icon="mdi:battery-minus",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="tripstat_efficiency",
        name="Trip efficiency",
        icon="mdi:car-cruise-control",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kWh/km",
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="tripstat_efficiency_dist",
        name="Trip efficiency distance",
        icon="mdi:car-cruise-control",
        device_class=SensorDeviceClass.DISTANCE,
        native_unit_of_measurement="km/kWh",
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="tripstat_speed",
        name="Trip speed",
        icon="mdi:speedometer",
        device_class=SensorDeviceClass.SPEED,
        native_unit_of_measurement=UnitOfSpeed.KILOMETERS_PER_HOUR,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="tripstat_prevefficiency",
        name="Previous trip efficiency",
        icon="mdi:car-cruise-control",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kWh/km",
        value=lambda data, key: data[key],
    ),
)

SENSORS_ChargeStat: tuple[SensorEntityDescription, ...] = (
    SensorEntityDesc(
        key="chargestat_distance",
        name="Charge distance",
        icon="mdi:map-marker-distance",
        device_class=SensorDeviceClass.DISTANCE,
        native_unit_of_measurement=UnitOfLength.KILOMETERS,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="chargestat_duration",
        name="Charge duration",
        icon="mdi:car-clock",
        device_class=SensorDeviceClass.DURATION,
        native_unit_of_measurement=None,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="chargestat_battery",
        name="Charge energy",
        icon="mdi:battery-plus",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="chargestat_efficiency",
        name="Charge efficiency",
        icon="mdi:car-cruise-control",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kWh/km",
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="chargestat_speed",
        name="Charge speed",
        icon="mdi:speedometer",
        device_class=SensorDeviceClass.SPEED,
        native_unit_of_measurement=UnitOfSpeed.KILOMETERS_PER_HOUR,
        value=lambda data, key: data[key],
    ),
    SensorEntityDesc(
        key="chargestat_prevefficiency",
        name="Previous charge efficiency",
        icon="mdi:car-cruise-control",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kWh/km",
        value=lambda data, key: data[key],
    ),
)
